### ISSUE TITLE
error `Illegal offset type` on fresh install

### ISSUE THREAD

**Issue by WimpyMistake** [aimeos/aimeos#14]
i just installed aimeos. then i navigated to my localhost and hit with this error

```
[2019-01-17 15:32:39] local.ERROR: Illegal offset type {"exception":"[object] (ErrorException(code: 0): Illegal offset type at /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Result/PDO.php:67)
[stacktrace]
#0 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Result/PDO.php(67): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Illegal offset ...', '/Users/username/Doc...', 67, Array)
#1 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Locale/Manager/Site/Standard.php(634): Aimeos\\MW\\DB\\Result\\PDO->fetch()
#2 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(475): Aimeos\\MShop\\Locale\\Manager\\Site\\Standard->searchItems(Object(Aimeos\\MW\\Criteria\\SQL), Array)
#3 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Locale/Manager/Site/Standard.php(348): Aimeos\\MShop\\Common\\Manager\\Base->findItemBase(Array, Array, false)
#4 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Decorator/Base.php(126): Aimeos\\MShop\\Locale\\Manager\\Site\\Standard->findItem('default', Array, 'product', NULL, false)
#5 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Locale/Manager/Standard.php(124): Aimeos\\MShop\\Common\\Manager\\Decorator\\Base->findItem('default')
#6 [internal function]: Aimeos\\MShop\\Locale\\Manager\\Standard->bootstrap('default', '', '', true)
#7 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Decorator/Base.php(51): call_user_func_array(Array, Array)
#8 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Base/Locale.php(71): Aimeos\\MShop\\Common\\Manager\\Decorator\\Base->__call('bootstrap', Array)
#9 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Base/Context.php(101): Aimeos\\Shop\\Base\\Locale->get(Object(Aimeos\\MShop\\Context\\Item\\Standard))
#10 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Base/Page.php(76): Aimeos\\Shop\\Base\\Context->get()
#11 /Users/username/Documents/apacheSites/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Controller/CatalogController.php(58): Aimeos\\Shop\\Base\\Page->getSections('catalog-list')
#12 [internal function]: Aimeos\\Shop\\Controller\\CatalogController->listAction()
#13 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('listAction', Array)
#15 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Aimeos\\Shop\\Controller\\CatalogController), 'listAction')
#16 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#17 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#18 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#39 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#40 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#41 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#42 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#43 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/username/Documents/apacheSites/myshop/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /Users/username/Documents/apacheSites/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#62 /Users/username/Documents/apacheSites/myshop/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 {main}
"} 

```

**environment**
- mac os mojave
- PHP 7.3.1 (with xdebug enabled. turned it off still yield same error)
- apache 2.4
- mysql 5.7
- Composer version 1.8.0
- aimeos was installed using `composer create-project aimeos/aimeos myshop` as per readme

** PrettyPage error in browser**
```
Environment & details:
GET Data empty
POST Data empty
Files empty
Cookies
XSRF-TOKEN	
"eyJpdiI6IlVDNm41dTVoTFgzKzE5VUlqV1VGTmc9PSIsInZhbHVlIjoiSFpsekc2R25lV3MwUXVRYVR3cU1rWG8rbXUzaTEzMTZ3WDZxc1wvY1wvXC9BQ1NZNWZGN3BuUjhycEJwNGVnb0Z2RyIsIm1hYyI6IjNh ▶"
aimeos_session	
"eyJpdiI6IlU3ZVhQMGJhZ1ZHQ3lRMlwvNzJ1OHhBPT0iLCJ2YWx1ZSI6ImFrV0dlbmNyQUNuVnQ2cWozVENJNmQzZVJSTVFsekZOUTgzbFBVN1JPOHRrSkVMb3ptMENWdmpEdmk0SkhHSEUiLCJtYWMiOiIxZGY0 ▶"
Session empty
Server/Request Data
REDIRECT_STATUS	
"200"
HTTP_HOST	
"myshop.test"
HTTP_CONNECTION	
"keep-alive"
HTTP_CACHE_CONTROL	
"max-age=0"
HTTP_UPGRADE_INSECURE_REQUESTS	
"1"
HTTP_USER_AGENT	
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
HTTP_DNT	
"1"
HTTP_ACCEPT	
"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
HTTP_ACCEPT_ENCODING	
"gzip, deflate"
HTTP_ACCEPT_LANGUAGE	
"en-US,en;q=0.9"
HTTP_COOKIE	
"XSRF-TOKEN=eyJpdiI6IlVDNm41dTVoTFgzKzE5VUlqV1VGTmc9PSIsInZhbHVlIjoiSFpsekc2R25lV3MwUXVRYVR3cU1rWG8rbXUzaTEzMTZ3WDZxc1wvY1wvXC9BQ1NZNWZGN3BuUjhycEJwNGVnb0Z2RyIsI ▶"
PATH	
"/usr/local/opt/php@7.0/sbin:/usr/local/opt/php@7.0/bin:/usr/local/opt/node@10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
SERVER_SIGNATURE	
""
SERVER_SOFTWARE	
"Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.1"
SERVER_NAME	
"myshop.test"
SERVER_ADDR	
"127.0.0.1"
SERVER_PORT	
"80"
REMOTE_ADDR	
"127.0.0.1"
DOCUMENT_ROOT	
"/Users/username/Documents/apacheSites/myshop/public"
REQUEST_SCHEME	
"http"
CONTEXT_PREFIX	
""
CONTEXT_DOCUMENT_ROOT	
"/Users/username/Documents/apacheSites/myshop/public"
SERVER_ADMIN	
"admin@myshop.test"
SCRIPT_FILENAME	
"/Users/username/Documents/apacheSites/myshop/public/index.php"
REMOTE_PORT	
"51853"
REDIRECT_URL	
"/list"
GATEWAY_INTERFACE	
"CGI/1.1"
SERVER_PROTOCOL	
"HTTP/1.1"
REQUEST_METHOD	
"GET"
QUERY_STRING	
""
REQUEST_URI	
"/list"
SCRIPT_NAME	
"/index.php"
PHP_SELF	
"/index.php"
REQUEST_TIME_FLOAT	
1547740430.353
REQUEST_TIME	
1547740430
APP_NAME	
"Aimeos"
APP_ENV	
"local"
APP_KEY	
"base64:rv/f2wj//8Gni9L9fxCo695vbT2nKjK9VOezUWef6YE="
APP_DEBUG	
"1"
APP_LOG_LEVEL	
"debug"
APP_URL	
"http://myshop.test"
DB_CONNECTION	
"mysql"
DB_HOST	
"127.0.0.1"
DB_PORT	
"3306"
DB_DATABASE	
"myshopdev"
DB_USERNAME	
"root"
DB_PASSWORD	
"password"
BROADCAST_DRIVER	
"log"
CACHE_DRIVER	
"file"
SESSION_DRIVER	
"file"
QUEUE_DRIVER	
"sync"
REDIS_HOST	
"127.0.0.1"
REDIS_PASSWORD	
""
REDIS_PORT	
"6379"
MAIL_DRIVER	
"smtp"
MAIL_HOST	
"smtp.mailtrap.io"
MAIL_PORT	
"2525"
MAIL_USERNAME	
""
MAIL_PASSWORD	
""
MAIL_ENCRYPTION	
""
PUSHER_APP_ID	
""
PUSHER_APP_KEY	
""
PUSHER_APP_SECRET	
""
```

**Comment by aimeos** [comment]
That looks like a bug in PHP 7.3: https://bugs.php.net/bug.php?id=77310

**Comment by WimpyMistake** [comment]
thanks for the prompt response!
you're right. downgraded to PHP 7.2 and the site is running well. thanks bunches
